<div class = "container">
    <h1>Najdi svého učitele</h1>
    <div class = "hledat">
        <form>
                <div class="hledat-ucitel">
                    <label>Učitel</label>
                    <input type="text" placeholder="Zadejte jméno a příjmení">
                </div>
            <button type="submit"><img src="/vendor/img/search.png"></button>
        </form>
    </div>
</div>
