<div class="container hledatD">
    <div class="row">
        <h1>Najdi svého učitele</h1>
    </div>

    <div class="hledat row">
        <form action="/vyhledejucitele" method=POST>
            <div class="hledat-ucitel">
                <label>Učitel</label>
                <input type="text" name="search" placeholder="Zadejte jméno a příjmení">
                <button type="submit"><img src="/vendor/img/search.png"></button>
            </div>
        </form>
    </div>
</div>