<canvas id="canvas" width=300 height=300 style="border: 1px solid black; margin-left: 10px; margin-top: 10px;"></canvas>

<p>Souradnice</p>
<p id="souradx"></p>
<p id="sourady"></p>

<br>

<br>

<br>

<br>

<h1>Vaše poloha:</h1>

<p id="text"></p>

<div id="m" style="height: 380px"></div>

<link rel="stylesheet" href="vendor/css/secret.css">

<script type="text/javascript" src="https://api.mapy.cz/loader.js"></script>
<script type="text/javascript">
    Loader.load();
</script>
<script type="text/javascript" src="/vendor/js/secret.js"></script>
<script type="text/javascript" src="/vendor/js/scr.js"></script>