<div class="container">
    <?php if (isset($school->obrazek)) : ?>
        <img style="height: 250px;" alt="<?= $school->nazev ?>-obrazek" src="<?= $school->obrazek ?>">
    <?php endif; ?>


    <h3><?= $school->nazev ?></h3>

    <p>
        Adresa:
        <?= $school->adresa ?>
    </p>

    <p>
        Kontaktní email:
        <?= $school->email ?>
    </p>

    <p>Průměrný počet hvězd: <?= number_format($hvezdy, 2) ?></p>

    <a href="/vytvorhodnoceniskola/<?= $school->id ?>">
        <button id="hodnoceniBtn">Napiš Hodnocení</button>
    </a>

    <br>



    <div class="container">

        <h3 class="nadpis">Učitelé v této škole</h3>
        <div class="container">
            <?php foreach ($ucitele as $ucitel) : ?>
                <article class=row>
                    <a href="/ucitel/<?= $ucitel["id"] ?>">
                        <p><?= $ucitel["jmeno"] ?></p>
                    </a>

                </article>

                <br>
            <?php endforeach; ?>
        </div>
    </div>

    <?php foreach ($hodnoceniskola as $hodnoceni) : ?>

        <article class=row>
            <p>
                Počet hvězd: <?= $hodnoceni["pocet_hvezd"] ?>
            </p>
            <p>
                Hodnocení: <?= $hodnoceni["zprava"] ?>
            </p>

            <form action="/skola/<?= $school->id ?>" method="POST">
                <input type="hidden" name="report_id" value="<?= $hodnoceni["id"] ?>">
                <input type="submit" name="report" value="Nahlaš Hodnocení">
            </form>

        </article>

        <br>

    <?php endforeach; ?>


</div>