<?php if(isset($schools)): ?>
    <section class=row>
        
        <div class="skolaNP">
            <h1>Školy</h1>
        </div>

        <div class="skoly">

        <?php foreach($schools as $school): ?>
            <article class=row>
                <?php if(isset($school["obrazek"])): ?>
                    <img style="height: 250px;" 
                    alt="<?= $school["nazev"] ?>-obrazek" 
                    src="<?= $school["obrazek"] ?>">
                <?php endif; ?>
                
                <a href="/skoly/<?= $school["id"] ?>">
                <h3><?= $school["nazev"] ?></h3>
                </a>
                
                <p>
                Adresa: 
                <?= $school["adresa"] ?>
                </p>
                
                <p>
                Kontaktní email:
                <?= $school["email"] ?>
                </p>
                
            </article>
            
            <br>
            <br>
        <?php endforeach; ?>

        </div>
    </section>
    
<?php endif; ?>