<div class="container">

    <?php if (isset($ucitel->obrazek)) : ?>
        <img style="height: 250px;" alt="<?= $ucitel->jmeno ?>-obrazek" src="<?= $ucitel->obrazek ?>">
    <?php endif; ?>

    <h3><?= $ucitel->jmeno ?></h3>

    <p>
        Kontaktní email:
        <?= $ucitel->email ?>
    </p>

    <a href="/skola/<?= $ucitel->skola_id ?>">
        <p>Pracuje v: <?= $ucitel->skola_nazev ?></p>
    </a>

    <a href="/vytvorhodnoceni/<?= $ucitel->id ?>">
        <button id="hodnoceniBtn">Napiš Hodnocení</button>
    </a>

    <br>

    <p>Průměrný počet hvězd: <?= number_format($hvezdy,2) ?></p>



    <?php foreach ($hodnocenii as $hodnoceni) : ?>

        <article class=row>
            <p>
                Počet hvězd: <?= $hodnoceni["pocet_hvezd"] ?>
            </p>
            <p>
                Hodnocení: <?= $hodnoceni["zprava"] ?>
            </p>

            <form action="/ucitel/<?= $ucitel->id ?>" method="POST">
                <input type="hidden" name="report_id" value="<?= $hodnoceni["id"] ?>">
                <input type="submit" name="report" value="Nahlaš Hodnocení">
            </form>


        </article>

        <br>

    <?php endforeach; ?>

</div>