<?php if (isset($ucitele)) : ?>
    <section>
        <div class="container">

            <div class="row" class="text-center">
                <h1>Učitelé</h1>
            </div>


            <div class="row text-center">

                <?php foreach ($ucitele as $ucitel) : ?>
                    <article class=row>

                        <?php if (isset($ucitel["obrazek"])) : ?>
                            <img style="height: 250px;" alt="<?= $ucitel["jmeno"] ?>-obrazek" src="<?= $ucitel["obrazek"] ?>">
                        <?php endif; ?>

                        <a href="/ucitel/<?= $ucitel["id"] ?>">
                            <h3><?= $ucitel["jmeno"] ?></h3>
                        </a>

                        <p>
                            Kontaktní email:
                            <?= $ucitel["email"] ?>
                        </p>

                    </article>

                    <br>
                    <br>
                <?php endforeach; ?>
            </div>

        </div>
    </section>

<?php endif; ?>