<?php if (isset($vyhledaniucitele)) : ?>
    <section>
        <div class="container">

            <div class="row" class="text-center">
                <h1 id="bigBoy" class="h1">Vyhledaní Učitelé</h1>
            </div>


            <div class="row text-center">

                <?php foreach ($vyhledaniucitele as $ucitel) : ?>
                    <article class=row>

                        <?php if (isset($ucitel["obrazek"])) : ?>
                            <img style="height: 250px;" alt="<?= $ucitel["jmeno"] ?>-obrazek" src="<?= $ucitel["obrazek"] ?>">
                        <?php endif; ?>



                        <a class="a" href="/ucitel/<?= $ucitel["id"] ?>">
                            <h3><?= $ucitel["jmeno"] ?></h3>
                        </a>

                        <p class="p">
                            Kontaktní email:
                            <?= $ucitel["email"] ?>
                        </p>

                        <a class="a" href="/skola/<?= $ucitel["skola_id"] ?>">
                            <p>Pracuje v: <?= $ucitel["nazev"] ?></p>
                        </a>

                    </article>

                    <br>
                    <br>
                <?php endforeach; ?>
            </div>

        </div>
    </section>

<?php endif; ?>

<div class="container hledatD">
    <div class="row">
        <h1 class="h1" id="bigBoy2">Najdi dalšího učitele</h1>
    </div>

    <div class="hledat row">
        <form action="/vyhledejucitele" method=POST>
            <div class="hledat-ucitel">
                <label style="color: black;">Učitel</label>
                <input type="text" name="search" placeholder="Zadejte jméno a příjmení">
                <button type="submit"><img src="/vendor/img/search.png"></button>
            </div>
        </form>
    </div>
</div>